/**
 * lib/skills/finance-pulse-general/types.ts
 *
 * Wave-4 discipline-wrap skill — finance. Closes the 8th discipline
 * (`docs/fleet-autonomy-audit-2026-05-28.md` §10 marked finance as
 * PARTIAL — only the per-vertical invoice-chasing-realestate + month-
 * end-close-cpa skills carried it). This horizontal closer drafts a
 * weekly read of the workspace's finance posture so every workspace —
 * not just CPA + realty — gets a finance discipline pulse.
 *
 * Per `project_no_outbound_architecture.md`: the skill READS state +
 * DRAFTS one row. Never sends to the customer.
 *
 * Per `feedback_runner_portability.md`: the snapshot reader + sink are
 * both ports the caller injects. QuickBooks access rides the existing
 * `QuickbooksMcpServer` interface — the skill does not import the
 * QuickBooks SDK or call the API directly.
 *
 * Per the honesty bar: when QuickBooks is NOT connected the snapshot
 * carries a `quickbooks: { connected: false, reason: ... }` shape. The
 * skill still fires + produces a row, but the body NAMES the gap and
 * does NOT fabricate AR / open-invoice / expense numbers.
 */

import type { SkillResult } from '../types';

/** QuickBooks-side counts the pulse grounds on when QB is connected.
 *  Every number is a count (never a dollar amount) so the operator can
 *  see scale without the skill claiming to read books. */
export interface FinanceQuickbooksSummary {
  /** Open (unpaid) invoices on file. */
  openInvoices: number;
  /** Open invoices past their dueDate as of `windowTo`. */
  overdueInvoices: number;
  /** Open invoices whose dueDate is more than 60 days past windowTo —
   *  the "deeply aged" bucket that warrants a phone call, not another
   *  draft email. */
  deeplyAgedInvoices: number;
  /** Customer count (capped at the MCP's pageable response). */
  activeCustomers: number;
  /** Expense count in window — proxies for "books need categorization"
   *  signal. */
  recentExpenses: number;
}

export type FinanceQuickbooksState =
  | { connected: true; summary: FinanceQuickbooksSummary }
  | {
      connected: false;
      reason:
        | 'not-connected'
        | 'credential-error'
        | 'upstream-error'
        | 'rate-limited';
      detail: string;
    };

/** Internal-signal counts every workspace generates — independent of
 *  QuickBooks. The pulse names the customer's financial-discipline
 *  activity from these even when QB is dark. */
export interface FinanceInternalCounts {
  /** Fires of `invoice-chasing-realestate` in window (proposals created). */
  invoiceChaseDrafts: number;
  /** Fires of `month-end-close-cpa` in window (proposals created). */
  monthEndCloseDrafts: number;
  /** Approvals across all finance-tagged kinds (discipline='finance')
   *  decided in window (approved + rejected). */
  financeApprovalsDecided: number;
  /** Pending finance approvals as of windowTo. */
  financeApprovalsPending: number;
  /** Learned notes captured from finance-tagged corrections. */
  learnedNotes: number;
}

export interface FinancePulseSnapshot {
  workspaceId: string;
  workspaceName: string;
  /** Workspace vertical — the pulse uses this to pick which signals it
   *  expects. A realty workspace with zero invoice-chase fires might
   *  still be on-trend; a CPA workspace with zero month-end-close fires
   *  is not. */
  workspaceVertical: string;
  windowFrom: string;
  windowTo: string;
  internal: FinanceInternalCounts;
  quickbooks: FinanceQuickbooksState;
}

export interface FinancePulseProposal {
  proposalId: string;
  /** ISO yyyy-MM-dd of the Monday at top of week. */
  forWeekStarting: string;
  body: string;
  snapshot: FinancePulseSnapshot;
  /** 0-3 short action bullets the operator could act on this week. */
  recommendations: string[];
  /** True when the body was generated by the LLM; false when the
   *  templated honest-fallback path emitted (quiet week / LLM error /
   *  malformed JSON). Surfaced on the approval card so the operator
   *  knows whether prose was composed. */
  llmComposed: boolean;
}

export interface FinancePulseApprovalSink {
  readonly name: string;
  record(args: {
    workspaceId: string;
    proposal: FinancePulseProposal;
  }): Promise<SkillResult<{ sinkId: string }>>;
}

export interface FinancePulseSkillInput {
  workspaceId: string;
  snapshot: FinancePulseSnapshot;
  sink?: FinancePulseApprovalSink;
  feedbackRulesBlock?: string;
  now?: Date;
  llm?: import('../../llm/types').LlmProvider;
  /** Workspace-tunable depth. `'summary'` (default) caps body length;
   *  `'detailed'` allows the LLM more tokens for the prose. */
  pulseDepth?: 'summary' | 'detailed';
}

export interface FinancePulseSkillOutput {
  proposal: FinancePulseProposal;
  sunk: boolean;
  noOutboundNote: string;
}

export const FINANCE_PULSE_AGENT_SLUG = 'finance-pulse-general';
export const FINANCE_PULSE_REF_TABLE = 'FinancePulseProposal';
