/* eslint-disable @next/next/no-img-element -- PlainoScene renders local
   /public brand rasters/SVGs with a plain <img>, not next/image, on purpose:
   the product + marketing surfaces are unit-tested with react-dom/server
   `renderToStaticMarkup` in bare node:test, where next/image's loader config
   is absent and would throw. A plain <img> renders identically server-side,
   in tests, and in OG/email contexts. See Plaino.tsx for the same rationale. */
import type { CSSProperties } from "react";

// PlainoScene — the single wiring contract for SCENE-LEVEL heritage Plaino
// illustrations (heroes, OG-adjacent motifs, auth welcome, in-app empty-state
// hero art). This is the larger, editorial sibling of `Plaino` (which is the
// small head-icon avatar) — it occupies a hero/empty-state slot, not an inline
// avatar.
//
// WHY THIS EXISTS (the non-blocking convention, per the Visual Gap Audit
// 2026-06-07 + Conner's non-blocking principle):
//   The audit found 25 PLACEHOLDER illustration slots that should host a
//   heritage Plaino scene but render text-only. We WIRE every slot through
//   this one component and ship a brand-correct placeholder stand-in now, so
//   the UX flow is reviewable. When Conner pastes the real ChatGPT-generated
//   asset back, swapping it in is a ONE-LINE change in the SRC map below —
//   every consuming surface picks it up automatically.
//
//   - `placeholder` srcs live at public/brand/plaino-system/placeholders/*.svg
//     (generated by tools/brand/gen-placeholder-scenes.mjs).
//   - `real` srcs are the swap targets at public/brand/plaino-system/scenes/*.png
//     (or an already-shipped pose/heritage asset). When a real file lands,
//     flip the entry from PLACEHOLDER(...) to a literal path string.
//   - The per-slot ChatGPT prompt for each real asset is indexed at
//     docs/brand/asset-prompts/README.md, keyed by the SAME slot name.

export type PlainoSceneName =
  // marketing
  | "home-crew"
  | "home-knowledge"
  | "home-future"
  | "pricing"
  | "custom"
  | "about-hero"
  | "about-dogfood"
  | "verticals"
  | "legal"
  | "inquiry-received"
  // auth
  | "auth-signin"
  | "auth-signup"
  | "auth-checkout"
  // in-app empty states
  | "empty-talk"
  | "empty-approvals"
  | "empty-activity"
  | "empty-sentinel"
  // per-vertical heroes
  | "vertical-real-estate"
  | "vertical-mortgage"
  | "vertical-insurance"
  | "vertical-property-management"
  | "vertical-title-escrow"
  | "vertical-recruiting"
  | "vertical-home-services"
  | "vertical-cpa"
  | "vertical-law"
  | "vertical-ria"
  | "vertical-general";

const PLACEHOLDERS = "/brand/plaino-system/placeholders";

// Map each slot to the placeholder SVG that stands in until the real asset
// lands. Each placeholder slug matches a target in gen-placeholder-scenes.mjs
// and a prompt entry in docs/brand/asset-prompts/README.md.
//
// SWAP CONTRACT: when Conner delivers a real asset, change the right-hand
// string here to the real path (e.g. "/brand/plaino-system/scenes/pricing.png")
// — nothing else changes anywhere in the app.
const SRC: Record<PlainoSceneName, string> = {
  "home-crew": `${PLACEHOLDERS}/home-crew-scene.svg`,
  "home-knowledge": `${PLACEHOLDERS}/home-knowledge-scene.svg`,
  "home-future": `${PLACEHOLDERS}/home-future-scene.svg`,
  pricing: `${PLACEHOLDERS}/pricing-hero.svg`,
  custom: `${PLACEHOLDERS}/custom-hero.svg`,
  "about-hero": `${PLACEHOLDERS}/about-hero.svg`,
  "about-dogfood": `${PLACEHOLDERS}/about-dogfood.svg`,
  verticals: `${PLACEHOLDERS}/verticals-hero.svg`,
  legal: `${PLACEHOLDERS}/legal-motif.svg`,
  "inquiry-received": `${PLACEHOLDERS}/inquiry-received.svg`,
  "auth-signin": `${PLACEHOLDERS}/auth-signin.svg`,
  "auth-signup": `${PLACEHOLDERS}/auth-signup.svg`,
  "auth-checkout": `${PLACEHOLDERS}/auth-checkout.svg`,
  "empty-talk": `${PLACEHOLDERS}/empty-talk.svg`,
  "empty-approvals": `${PLACEHOLDERS}/empty-approvals.svg`,
  "empty-activity": `${PLACEHOLDERS}/empty-activity.svg`,
  "empty-sentinel": `${PLACEHOLDERS}/empty-sentinel.svg`,
  "vertical-real-estate": `${PLACEHOLDERS}/vertical-real-estate.svg`,
  "vertical-mortgage": `${PLACEHOLDERS}/vertical-mortgage.svg`,
  "vertical-insurance": `${PLACEHOLDERS}/vertical-insurance.svg`,
  "vertical-property-management": `${PLACEHOLDERS}/vertical-property-management.svg`,
  "vertical-title-escrow": `${PLACEHOLDERS}/vertical-title-escrow.svg`,
  "vertical-recruiting": `${PLACEHOLDERS}/vertical-recruiting.svg`,
  "vertical-home-services": `${PLACEHOLDERS}/vertical-home-services.svg`,
  "vertical-cpa": `${PLACEHOLDERS}/vertical-cpa.svg`,
  "vertical-law": `${PLACEHOLDERS}/vertical-law.svg`,
  "vertical-ria": `${PLACEHOLDERS}/vertical-ria.svg`,
  "vertical-general": `${PLACEHOLDERS}/vertical-general.svg`,
};

// True when the slot is still wired to a placeholder (vs. a delivered real
// asset). Used by the wiring test to assert every slot resolves to SOMETHING
// renderable, and lets a surface choose to flag a slot as not-yet-final.
export function isPlaceholderScene(name: PlainoSceneName): boolean {
  return SRC[name].startsWith(PLACEHOLDERS);
}

// Resolve a vertical slug to its scene name; falls back to the /general
// on-ramp scene for any slug without a dedicated hero (keeps a misrouted
// render valid instead of blank).
export function verticalSceneName(slug: string): PlainoSceneName {
  const candidate = `vertical-${slug}` as PlainoSceneName;
  return candidate in SRC ? candidate : "vertical-general";
}

type Props = {
  name: PlainoSceneName;
  /** Accessible label. Omit to render decorative (aria-hidden). */
  alt?: string;
  className?: string;
  style?: CSSProperties;
};

export function PlainoScene({ name, alt, className, style }: Props) {
  const decorative = !alt;
  return (
    <img
      src={SRC[name]}
      alt={alt ?? ""}
      className={className}
      style={style}
      aria-hidden={decorative || undefined}
      data-plaino-scene={name}
      data-plaino-placeholder={isPlaceholderScene(name) || undefined}
    />
  );
}

export default PlainoScene;
