/* eslint-disable @next/next/no-img-element -- PlainoScene renders local
   /public brand rasters/SVGs with a plain <img>, not next/image, on purpose:
   the product + marketing surfaces are unit-tested with react-dom/server
   `renderToStaticMarkup` in bare node:test, where next/image's loader config
   is absent and would throw. A plain <img> renders identically server-side,
   in tests, and in OG/email contexts. See Plaino.tsx for the same rationale. */
import type { CSSProperties } from "react";

// PlainoScene — the single wiring contract for SCENE-LEVEL heritage Plaino
// illustrations (heroes, OG-adjacent motifs, auth welcome, in-app empty-state
// hero art). This is the larger, editorial sibling of `Plaino` (which is the
// small head-icon avatar) — it occupies a hero/empty-state slot, not an inline
// avatar.
//
// TWO ASSET TIERS in the SRC map:
//   1. REAL DOG POSES — auth, empty-state, and character slots point directly at
//      clean re-cropped PNG poses from the reference sheet (sitting-alert, fetching,
//      standing-watch, guarding, resting). These ship now and render the brand beagle.
//   2. PRAIRIE MOTIF SVGs — marketing hero and structural slots point at brand-correct
//      prairie compositions (generated by tools/brand/gen-placeholder-scenes.mjs).
//      When Conner delivers real raster scenes, flip the entry to the new path —
//      every consuming surface picks it up automatically.
//
//   SWAP CONTRACT: change the right-hand string in SRC to the new path.
//   Real poses: /brand/plaino-system/poses/<slug>.png
//   Motif SVGs: /brand/plaino-system/placeholders/<slug>.svg
//   Delivered scenes: /brand/plaino-system/scenes/<slug>.png

export type PlainoSceneName =
  // marketing
  | "home-crew"
  | "home-knowledge"
  | "home-future"
  | "pricing"
  | "custom"
  | "about-hero"
  | "about-dogfood"
  | "verticals"
  | "legal"
  | "inquiry-received"
  // auth
  | "auth-signin"
  | "auth-signup"
  | "auth-checkout"
  // in-app empty states
  | "empty-talk"
  | "empty-approvals"
  | "empty-activity"
  | "empty-sentinel"
  // per-vertical heroes
  | "vertical-real-estate"
  | "vertical-mortgage"
  | "vertical-insurance"
  | "vertical-property-management"
  | "vertical-title-escrow"
  | "vertical-recruiting"
  | "vertical-home-services"
  | "vertical-cpa"
  | "vertical-law"
  | "vertical-ria"
  | "vertical-general";

const PLACEHOLDERS = "/brand/plaino-system/placeholders";
const POSES = "/brand/plaino-system/poses";

// SRC map — two tiers:
//   REAL POSE PNGs: auth gates, empty states, inquiry-received, about-dogfood.
//     The brand beagle renders now. Object-fit: contain handles portrait crops.
//   PRAIRIE MOTIF SVGs: marketing heroes, structural slots, per-vertical heroes.
//     Brand-correct compositions. Swap to real PNG when delivered.
const SRC: Record<PlainoSceneName, string> = {
  // ── Marketing / structural — prairie motif SVGs ───────────────────────────
  "home-crew":      `${PLACEHOLDERS}/home-crew-scene.svg`,
  "home-knowledge": `${PLACEHOLDERS}/home-knowledge-scene.svg`,
  "home-future":    `${PLACEHOLDERS}/home-future-scene.svg`,
  pricing:          `${PLACEHOLDERS}/pricing-hero.svg`,
  custom:           `${PLACEHOLDERS}/custom-hero.svg`,
  "about-hero":     `${PLACEHOLDERS}/about-hero.svg`,
  verticals:        `${PLACEHOLDERS}/verticals-hero.svg`,
  legal:            `${PLACEHOLDERS}/legal-motif.svg`,

  // ── Character slots — real brand beagle PNGs ─────────────────────────────
  // Auth: sitting-alert (waiting/ready), fetching (bringing work home)
  "auth-signin":    `${POSES}/sitting-alert.png`,
  "auth-signup":    `${POSES}/sitting-alert.png`,
  "auth-checkout":  `${POSES}/fetching.png`,
  // Inquiry received: fetching (work delivered)
  "inquiry-received": `${POSES}/fetching.png`,
  // About dogfood: resting (even working dogs take a break)
  "about-dogfood":  `${POSES}/resting.png`,
  // In-app empty states
  "empty-talk":       `${POSES}/sitting-alert.png`,  // here when ready
  "empty-approvals":  `${POSES}/fetching.png`,        // caught up
  "empty-activity":   `${POSES}/standing-watch.png`,  // on watch
  "empty-sentinel":   `${POSES}/guarding.png`,         // holding the line

  // ── Per-vertical heroes — prairie motif SVGs ─────────────────────────────
  "vertical-real-estate":         `${PLACEHOLDERS}/vertical-real-estate.svg`,
  "vertical-mortgage":            `${PLACEHOLDERS}/vertical-mortgage.svg`,
  "vertical-insurance":           `${PLACEHOLDERS}/vertical-insurance.svg`,
  "vertical-property-management": `${PLACEHOLDERS}/vertical-property-management.svg`,
  "vertical-title-escrow":        `${PLACEHOLDERS}/vertical-title-escrow.svg`,
  "vertical-recruiting":          `${PLACEHOLDERS}/vertical-recruiting.svg`,
  "vertical-home-services":       `${PLACEHOLDERS}/vertical-home-services.svg`,
  "vertical-cpa":                 `${PLACEHOLDERS}/vertical-cpa.svg`,
  "vertical-law":                 `${PLACEHOLDERS}/vertical-law.svg`,
  "vertical-ria":                 `${PLACEHOLDERS}/vertical-ria.svg`,
  "vertical-general":             `${PLACEHOLDERS}/vertical-general.svg`,
};

// True when the slot is still wired to a prairie motif SVG (awaiting a real
// raster scene delivery). Slots backed by a pose PNG or a delivered scene are
// considered final. Used by the wiring test.
export function isPlaceholderScene(name: PlainoSceneName): boolean {
  return SRC[name].startsWith(PLACEHOLDERS);
}

// Resolve a vertical slug to its scene name; falls back to the /general
// on-ramp scene for any slug without a dedicated hero (keeps a misrouted
// render valid instead of blank).
export function verticalSceneName(slug: string): PlainoSceneName {
  const candidate = `vertical-${slug}` as PlainoSceneName;
  return candidate in SRC ? candidate : "vertical-general";
}

type Props = {
  name: PlainoSceneName;
  /** Accessible label. Omit to render decorative (aria-hidden). */
  alt?: string;
  className?: string;
  style?: CSSProperties;
};

export function PlainoScene({ name, alt, className, style }: Props) {
  const decorative = !alt;
  return (
    <img
      src={SRC[name]}
      alt={alt ?? ""}
      className={className}
      style={style}
      aria-hidden={decorative || undefined}
      data-plaino-scene={name}
      data-plaino-placeholder={isPlaceholderScene(name) || undefined}
    />
  );
}

export default PlainoScene;
