/**
 * lib/skills/insurance-coi-request/types.ts
 *
 * Provider-neutral types for the insurance brokerage's certificate-of-
 * insurance (COI) request workflow. The skill reads an inbound COI
 * request, looks up the named-insured's policies through the agency's
 * AMS, builds a structured COI payload (named insured + additional
 * insureds + per-line coverage references), and drafts a formal note to
 * the requester confirming receipt + next steps.
 *
 * Per `lib/skills/prompts/insurance.ts` `draftToneGuidance`:
 *   - never quote a premium — defer with `{{operator: premium}}`
 *   - never confirm a binding / effective date — defer with
 *     `{{operator: bind/effective date}}` until the carrier portal echoes
 *   - never use words like "guarantee" or "ensure"
 *   - always note "subject to underwriting" for any new-line request
 *
 * Per `feedback_no_silent_vendor_lock.md`: AMS SDKs (EZLynx / Applied
 * Epic / AMS360 / HawkSoft) stay behind the `PolicyLookup` port.
 *
 * Per `project_no_outbound_architecture.md`: DRAFTS only — agentplain
 * never issues the certificate itself. The CSR / producer reviews the
 * payload, opens it in the AMS or the carrier portal, and issues from
 * there. The chase-reply draft persists to the email port.
 */

import type { DraftPersister, SkillResult } from '../types';

// ── Input shapes ─────────────────────────────────────────────────────────

export type CoverageLine =
  | 'general-liability'
  | 'auto-liability'
  | 'workers-comp'
  | 'umbrella'
  | 'professional-liability'
  | 'property'
  | 'inland-marine';

export interface ContactPerson {
  name: string;
  email: string;
}

/**
 * The party requesting the certificate. Usually a project owner, a
 * landlord, a general contractor, or a vendor coordinator — someone who
 * needs proof of coverage before they let the insured on a job or sign
 * a contract.
 */
export interface CoiRequester {
  /** Company name appearing on the certificate holder line. */
  organizationName: string;
  /** Primary contact who emailed the request. */
  contact: ContactPerson;
  /** Specific project / contract reference the requester named. May be
   *  empty when the requester just wants a generic certificate on file. */
  projectReference: string | null;
}

/**
 * The insured business the agency manages — the entity whose policies
 * back the certificate.
 */
export interface NamedInsured {
  /** Account display name in the AMS. */
  displayName: string;
  /** Legal name as it appears on policy declarations. */
  legalName: string;
  /** Primary contact at the insured (CC'd on the chase reply). */
  contact: ContactPerson;
}

/**
 * One policy row from the agency's AMS. The skill cares about
 * cross-policy coverage coverage of the request, NOT about premium or
 * carrier-specific limit math (which always defers to {{operator: ...}}).
 */
export interface PolicyOnFile {
  /** Policy number from the AMS. */
  policyNumber: string;
  /** Carrier name as recorded in the AMS. */
  carrierName: string;
  /** Coverage line this policy provides. */
  line: CoverageLine;
  /** ISO date the policy term ends; used to spot expired policies. */
  expirationDate: string;
  /** Whether this policy is currently in force (not cancelled / non-renewed). */
  inForce: boolean;
}

export interface CoiRequestRecord {
  /** Stable id for the request — populated by the AMS or generated by
   *  the inbox classifier when it first surfaces the COI ask. */
  requestId: string;
  /** The COI requester. */
  requester: CoiRequester;
  /** The named insured the certificate is on. */
  insured: NamedInsured;
  /** Coverage lines the requester asked be shown on the certificate.
   *  Comes from the inbound message parser; tests can supply directly. */
  requestedLines: CoverageLine[];
  /** Whether the requester asked to be added as ADDITIONAL INSURED
   *  (typical for landlord / GC / project-owner requests). */
  additionalInsured: boolean;
  /** Whether the requester asked for a WAIVER OF SUBROGATION. */
  waiverOfSubrogation: boolean;
  /** Whether the request flagged a deadline ("need this by Friday"). */
  hasDeadline: boolean;
  /** CSR / producer responsible for the account — the chase reply is
   *  signed by this person. */
  responsibleCsr: ContactPerson;
  /** Free-text body of the inbound request — surfaces in the audit log
   *  for the CSR's review (never sent back to the requester verbatim). */
  rawRequestBody: string;
}

export interface PolicyLookup {
  readonly name: string;
  fetchPoliciesForInsured(args: {
    workspaceId: string;
    insuredLegalName: string;
  }): Promise<SkillResult<PolicyOnFile[]>>;
}

// ── Output shapes ────────────────────────────────────────────────────────

export type CoverageMatch = 'in-force' | 'expired' | 'not-on-file';

export interface CoverageDecision {
  line: CoverageLine;
  match: CoverageMatch;
  /** When `match === 'in-force'`, the policy on the AMS that backs the
   *  certificate. NULL otherwise. */
  policy: PolicyOnFile | null;
}

/**
 * Structured payload the CSR opens in the AMS or carrier portal to
 * actually issue the certificate. The skill builds it; the human issues.
 */
export interface CoiIssuancePayload {
  certificateHolder: string;
  insuredLegalName: string;
  /** True when the requester asked to be added as additional insured. */
  additionalInsured: boolean;
  /** True when the requester asked for a waiver of subrogation. */
  waiverOfSubrogation: boolean;
  /** Project / contract reference the requester named (may be empty). */
  projectReference: string | null;
  /** One row per coverage line — covers both in-force and gap rows so the
   *  CSR sees what is missing before opening the carrier portal. */
  coverageDecisions: CoverageDecision[];
}

export type RequestStatus =
  | 'ready-to-issue'
  | 'coverage-gap'
  | 'expired-coverage'
  | 'needs-operator-review';

export interface RequesterReplyDraft {
  draftId: string;
  providerDraftId: string | null;
  toEmails: string[];
  ccEmails: string[];
  subject: string;
  body: string;
  tone: 'formal';
  confidence: number;
  persisted: boolean;
}

export interface CoiRequestOutput {
  requestId: string;
  status: RequestStatus;
  /** Issuance payload the CSR opens in the AMS / carrier portal. */
  issuance: CoiIssuancePayload;
  /** Draft reply back to the requester confirming receipt + next step. */
  requesterReply: RequesterReplyDraft;
}

export interface CoiRequestInput {
  workspaceId: string;
  request: CoiRequestRecord;
  lookup: PolicyLookup;
  persister?: DraftPersister | null;
  persistThreshold?: number;
  /** Optional clock for deterministic tests. */
  now?: Date;
}

export const DEFAULT_PERSIST_THRESHOLD = 0.5;
