/**
 * Snapshot-backed `LeadershipDataSource`.
 *
 * v1 implementation. The snapshot is a JSON file at
 * `public/leadership-snapshot.json`, regenerated by
 * `scripts/snapshot-leadership-state.ts`. We read it through `fs` rather
 * than `fetch` so the page works in build / preview / production without
 * a network hop and without bundling a giant JSON blob into the route.
 *
 * Per `feedback_runner_portability.md`: this file is one of two intended
 * `LeadershipDataSource` implementations. The other — `LeadershipDataDb`
 * (DB-backed AgentRunLog) — lands in v2 and slots in without changes to
 * the page, the classifier, or the snapshot shape.
 *
 * Per `feedback_no_guesses_no_estimates.md`: if the file is missing or
 * malformed, the source returns `EMPTY_SNAPSHOT` and never fabricates
 * observations.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import {
  EMPTY_SNAPSHOT,
  parseSnapshot,
  type LeadershipDataSource,
  type LeadershipSnapshot,
} from "./leadership-data";

export interface SnapshotSourceOptions {
  /** Absolute path to `public/leadership-snapshot.json`. Override is
   *  test-only. */
  snapshotPath?: string;
  /** Test-only override of `fs.readFile`. */
  readFileImpl?: (filePath: string) => Promise<string>;
}

export class LeadershipDataSnapshotSource implements LeadershipDataSource {
  private readonly snapshotPath: string;
  private readonly readFileImpl: (filePath: string) => Promise<string>;

  constructor(options: SnapshotSourceOptions = {}) {
    this.snapshotPath =
      options.snapshotPath ??
      path.join(process.cwd(), "public", "leadership-snapshot.json");
    this.readFileImpl =
      options.readFileImpl ?? ((p: string) => readFile(p, "utf8"));
  }

  async load(): Promise<LeadershipSnapshot> {
    let raw: string;
    try {
      raw = await this.readFileImpl(this.snapshotPath);
    } catch (err: unknown) {
      // ENOENT is the empty-state path: no script has been run yet.
      const code = (err as NodeJS.ErrnoException | undefined)?.code;
      if (code === "ENOENT") return EMPTY_SNAPSHOT;
      throw err;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return EMPTY_SNAPSHOT;
    }
    try {
      return parseSnapshot(parsed);
    } catch {
      return EMPTY_SNAPSHOT;
    }
  }
}

/** Default singleton, used by the page. Tests build their own with a
 *  custom `readFileImpl`. */
export const defaultLeadershipDataSource = new LeadershipDataSnapshotSource();
