// Charlotte Mason philosophy pack — canonical loader.
//
// This module assembles the typed pack the agents consume:
//   Integrator      → lesson_shape, weekly_rhythms, daily_rhythm, scheduling_notes, living_books
//   Headmaster      → assessment, good_day_definition, weekly_rhythms
//   Tutor-Advisor   → daily_question_style, narration
//   All agents      → citations (rule_refs let a reasoning trace point at the
//                     exact pack section it applied, e.g.
//                     "lesson_shape.max_block_minutes_by_age[6]=15")
//
// pack.json in this directory is the serialized form of the same object for
// non-TypeScript consumers, regenerated by `npm run pack:build`. The TS
// modules are the source of truth; `npm run pack:verify` fails if the two
// drift, if any citation's rule_ref points at a path that does not exist, or
// if any parent-facing string breaks the vendor-invisibility rule.
import type {
  CharlotteMasonPack,
  CriterionEntry,
  InterpretationNote,
} from "./types";
import { lessonShape, maxBlockMinutesForAge } from "./lesson-shape";
import { dailyRhythm } from "./daily-rhythm";
import { weeklyRhythms } from "./weekly-rhythms";
import { narration, goodDayDefinition } from "./narration";
import { livingBooks } from "./living-books";
import { natureStudy } from "./nature-study";
import { handicrafts } from "./handicrafts";
import { habitFormation } from "./habits";
import { assessment } from "./assessment";
import { citations, citationsForRule } from "./citations";

// The load-bearing principles from Vol VI's 20-principle synopsis (and their
// Vol III forerunners). The Headmaster frames the week's vision in these
// terms; each carries the citation its reasoning trace should point at.
const firstPrinciples: CriterionEntry[] = [
  {
    text:
      "Children are born persons — a complete person now, owed real ideas " +
      "and real books, never a vessel to fill or a project to manage.",
    basis: "mason",
    cite: ["vol6-born-persons"],
  },
  {
    text:
      "Education is an atmosphere, a discipline, a life: the real home " +
      "environment, the steady formation of habits, and living ideas are " +
      "the only three instruments the educator has.",
    basis: "mason",
    cite: ["vol6-atmosphere-discipline-life", "vol3-atmosphere"],
  },
  {
    text:
      "Education is the science of relations — the child's business is to " +
      "form firsthand relationships with the natural world, books, and " +
      "people, so the curriculum is generous and wide.",
    basis: "mason",
    cite: ["vol6-science-of-relations", "vol6-mind-feeds-on-ideas", "vol3-wide-curriculum"],
  },
  {
    text:
      "There is no education but self-education: what the child digs out " +
      "and tells back is what they own. The teacher spreads the feast and " +
      "gets out of the way.",
    basis: "mason",
    cite: ["vol6-self-education", "vol6-act-of-knowing"],
  },
  {
    text:
      "The habit of attention is the master habit; every short lesson is " +
      "itself attention training.",
    basis: "mason",
    cite: ["vol1-habit-of-attention", "vol1-short-lessons"],
  },
  {
    text:
      "Older students are taught the way of the will and the way of reason " +
      "— self-management by turning the thoughts, and a just suspicion of " +
      "one's own too-confident conclusions.",
    basis: "mason",
    cite: ["vol6-way-of-will"],
  },
];

const interpretationNotes: InterpretationNote[] = [
  {
    rule_ref: "lesson_shape.stage_notes",
    note:
      "Mason organized children into Forms (I–VI), not the trivium stages " +
      "this app uses. The grammar/logic/rhetoric keys are our bridge to the " +
      "app's Stage type; the Form-to-age bands underneath are hers, via " +
      "PNEU practice [pneu-forms-ages].",
  },
  {
    rule_ref: "lesson_shape.max_block_minutes_by_age",
    note:
      "Under eight, the 20-minute ceiling is Mason's own. The per-age steps " +
      "above that interpolate the printed PNEU per-Form lesson lengths onto " +
      "single ages, and ages 17–18 extend the Form V–VI band — both are our " +
      "application, kept because the Integrator needs an integer per age.",
  },
  {
    rule_ref: "habit_formation.duration",
    note:
      "Mason says forming a good habit is 'the work of a few weeks' and " +
      "names no fixed number. 'About six weeks' is our planning default " +
      "chosen to honor her warnings against stopping early; treat it as a " +
      "floor for focus, not a guarantee of formation.",
  },
  {
    rule_ref: "narration.quality_signals",
    note:
      "The quality/anti-signal lists operationalize her descriptions of " +
      "good and bad telling for model-update extraction. Consistent with " +
      "her examples; the list itself is ours.",
  },
  {
    rule_ref: "handicrafts.age_appropriate",
    note:
      "The craft names come from PNEU programme practice; their exact " +
      "age placement is our application of her 'within their compass' rule.",
  },
  {
    rule_ref: "weekly_rhythms",
    note:
      "'One composer per term' and 'one Shakespeare play per term' are PNEU " +
      "Parents' Union School programme practice. Vol VI confirms the termly " +
      "music programme and Shakespeare-by-Form-II, but the per-term formulas " +
      "come from the programmes, not her prose.",
  },
  {
    rule_ref: "nature_study.seasonal_focus",
    note:
      "Mason insists on year-round outdoor life; the specific per-season " +
      "observation menus are our suggestions in that spirit.",
  },
];

export const charlotteMasonPack: CharlotteMasonPack = {
  id: "charlotte-mason",
  name: "Charlotte Mason",
  founder: "Charlotte M. Mason (1842–1923)",
  version: 2, // v1 was the M1 research stub (docs/research/philosophies/charlotte-mason.md)

  core_texts: [
    {
      title: "Home Education",
      volume_number: 1,
      year: 1886,
      public_domain: true,
      canonical_url: "https://www.amblesideonline.org/CM/vol1complete.html",
    },
    {
      title: "Parents and Children",
      volume_number: 2,
      year: 1896,
      public_domain: true,
      canonical_url: "https://www.amblesideonline.org/CM/vol2complete.html",
    },
    {
      title: "School Education",
      volume_number: 3,
      year: 1904,
      public_domain: true,
      canonical_url: "https://www.amblesideonline.org/CM/vol3complete.html",
    },
    {
      title: "Ourselves",
      volume_number: 4,
      year: 1904,
      public_domain: true,
      canonical_url: "https://www.amblesideonline.org/CM/vol4complete.html",
    },
    {
      title: "Formation of Character",
      volume_number: 5,
      year: 1906,
      public_domain: true,
      canonical_url: "https://www.amblesideonline.org/CM/vol5complete.html",
    },
    {
      title: "Towards a Philosophy of Education",
      volume_number: 6,
      year: 1923,
      public_domain: true,
      canonical_url: "https://www.amblesideonline.org/CM/vol6complete.html",
    },
  ],

  first_principles: firstPrinciples,
  lesson_shape: lessonShape,
  daily_question_style: "narration",
  narration,
  good_day_definition: goodDayDefinition,
  weekly_rhythms: weeklyRhythms,
  daily_rhythm: dailyRhythm,

  scheduling_notes:
    "Mornings carry all the demanding work, as a run of short, varied, " +
    "hard-capped blocks from 9:00; afternoons are structurally free for " +
    "outdoor life, the nature walk, and handicrafts — never book lessons. " +
    "Habit training is background, not a subject block. Three terms of " +
    "about twelve weeks shape the year, each with its own artist, composer, " +
    "and hymn, closing in an exam week answered by narration.",

  living_books: livingBooks,
  nature_study: natureStudy,
  handicrafts,
  habit_formation: habitFormation,
  assessment,
  interpretation_notes: interpretationNotes,
  citations,
};

export default charlotteMasonPack;
export { maxBlockMinutesForAge, citationsForRule, goodDayDefinition };
export type { CharlotteMasonPack } from "./types";
