/**
 * scripts/render-counsel-handoff-packets.ts
 *
 * Renders the per-vertical counsel-handoff packets to
 * `outputs/counsel-handoff-packets/<vertical>.md` so Conner can hand the
 * markdown directly to outside counsel without exposing the codebase.
 *
 * Run: `npx tsx scripts/render-counsel-handoff-packets.ts`
 *
 * Per `feedback_no_guesses_no_estimates.md`: every section in the output
 * cites the source file the data came from — no synthesis, no smoothing
 * over of the corpus contents.
 *
 * Per the 2026-05-25 vertical-depth wave: the rendered packets are
 * counsel PREP material. They explicitly carry the DRAFT badge and the
 * "sentinel is not firing on these yet" disclaimer at the top so counsel
 * is not misled about deployment state.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  buildCounselHandoffPacket,
  listCorpusVerticals,
  loadCorpusFor,
  type CounselHandoffPacket,
} from "../lib/agents/sentinel";

const OUT_DIR = path.resolve(process.cwd(), "outputs/counsel-handoff-packets");

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const slugs = listCorpusVerticals();
  for (const slug of slugs) {
    const corpus = loadCorpusFor(slug);
    if (!corpus) continue;
    const packet = buildCounselHandoffPacket(corpus);
    const md = renderPacketMarkdown(slug, packet);
    const file = path.join(OUT_DIR, `${slug}.md`);
    await writeFile(file, md, "utf8");
    process.stdout.write(`wrote ${path.relative(process.cwd(), file)}\n`);
  }
  const index = renderIndex(slugs);
  const indexPath = path.join(OUT_DIR, "README.md");
  await writeFile(indexPath, index, "utf8");
  process.stdout.write(`wrote ${path.relative(process.cwd(), indexPath)}\n`);
}

function renderPacketMarkdown(slug: string, packet: CounselHandoffPacket): string {
  const lines: string[] = [];
  lines.push(`# Counsel-handoff packet — ${slug}`);
  lines.push("");
  lines.push(`> **Status: ${packet.status}** — counsel reviewer: ${packet.counselReviewer ?? "_not yet assigned_"}`);
  lines.push(`> Generated by \`scripts/render-counsel-handoff-packets.ts\` from the corpus rule files under \`lib/agents/sentinel/corpus/${slug}/\`.`);
  lines.push("");
  lines.push("## Important context for counsel");
  lines.push("");
  lines.push("- This corpus is **DRAFT**. Sentinel does not currently fire on this vertical's content.");
  lines.push("- The **Candidate literal triggers** section below is the bucket we need your phrase-by-phrase red-line on. Each phrase was drafted from a published regulatory source and carries a citation, but the agentplain team has NOT verified that the phrase is the right literal trigger for sentinel to fire on. Approve / reword / demote to counsel-reference / strike each phrase.");
  lines.push("- The **Counsel references** section is regulatory text that sentinel does not literal-match against — it requires generative judgment. We're surfacing it so you see the substantive law backing the trigger list.");
  lines.push("- Sentinel will not flip live for this vertical until you sign off on the corpus.");
  lines.push("");
  lines.push(`_Last reviewed: ${packet.lastReviewedAt}_`);
  lines.push("");

  lines.push("## Open questions for counsel");
  lines.push("");
  if (packet.openQuestions.length === 0) {
    lines.push("_No open questions recorded._");
  } else {
    for (const q of packet.openQuestions) {
      lines.push(`- ${q}`);
    }
  }
  lines.push("");

  lines.push(`## Live literal triggers (${packet.literalTriggers.length})`);
  lines.push("");
  if (packet.literalTriggers.length === 0) {
    lines.push("_None. Sentinel is not firing on any literal phrase in this vertical's corpus today._");
  } else {
    lines.push(renderLiteralTriggerTable(packet.literalTriggers));
  }
  lines.push("");

  lines.push(`## Candidate literal triggers — for counsel red-line (${packet.candidateLiteralTriggers.length})`);
  lines.push("");
  if (packet.candidateLiteralTriggers.length === 0) {
    lines.push("_No candidate phrases drafted for this vertical. If you believe one is appropriate, please flag in counsel review._");
  } else {
    const byRule = new Map<string, typeof packet.candidateLiteralTriggers>();
    for (const t of packet.candidateLiteralTriggers) {
      const arr = byRule.get(t.ruleId) ?? [];
      arr.push(t);
      byRule.set(t.ruleId, arr);
    }
    for (const [ruleId, triggers] of byRule) {
      const first = triggers[0];
      lines.push(`### ${first.ruleTitle}`);
      lines.push("");
      lines.push(`- **Rule id:** \`${ruleId}\``);
      lines.push(`- **Citation:** ${first.citation.source}`);
      lines.push(`- **URL:** ${first.citation.url}`);
      lines.push(`- **Accessed:** ${first.citation.accessedAt}`);
      if (first.drafterNotes) {
        lines.push("");
        lines.push(`**Drafter notes:** ${first.drafterNotes}`);
      }
      lines.push("");
      lines.push("| # | Candidate phrase | Category |");
      lines.push("| --- | --- | --- |");
      triggers.forEach((t, i) => {
        lines.push(`| ${i + 1} | \`${t.phrase}\` | ${t.category ?? "—"} |`);
      });
      lines.push("");
    }
  }

  lines.push(`## Counsel references (${packet.counselReferences.length})`);
  lines.push("");
  if (packet.counselReferences.length === 0) {
    lines.push("_No counsel-reference rules in this corpus._");
  } else {
    for (const ref of packet.counselReferences) {
      lines.push(`### ${ref.ruleTitle}`);
      lines.push("");
      lines.push(`- **Rule id:** \`${ref.ruleId}\``);
      lines.push(`- **Citation:** ${ref.citation.source}`);
      lines.push(`- **URL:** ${ref.citation.url}`);
      lines.push(`- **Accessed:** ${ref.citation.accessedAt}`);
      lines.push("");
      lines.push(`**Summary:** ${ref.summary}`);
      lines.push("");
      lines.push("**Literal text:**");
      lines.push("");
      lines.push("```text");
      lines.push(ref.literalText);
      lines.push("```");
      lines.push("");
    }
  }

  return lines.join("\n");
}

function renderLiteralTriggerTable(triggers: CounselHandoffPacket["literalTriggers"]): string {
  const rows: string[] = [];
  rows.push("| # | Phrase | Rule | Citation |");
  rows.push("| --- | --- | --- | --- |");
  triggers.forEach((t, i) => {
    rows.push(`| ${i + 1} | \`${t.phrase}\` | ${t.ruleTitle} | ${t.citation.source} |`);
  });
  return rows.join("\n");
}

function renderIndex(slugs: string[]): string {
  const lines: string[] = [];
  lines.push("# Counsel-handoff packets — index");
  lines.push("");
  lines.push("Per-vertical packets generated by `scripts/render-counsel-handoff-packets.ts` from the sentinel corpus under `lib/agents/sentinel/corpus/`.");
  lines.push("");
  lines.push("**For counsel:** each linked file contains (a) live literal triggers sentinel currently fires on, (b) candidate literal triggers awaiting phrase-by-phrase red-line, (c) counsel-reference regulatory text for context, and (d) open questions the agentplain team needs your input on.");
  lines.push("");
  lines.push("Every corpus below is DRAFT. Sentinel does not flip live for any vertical until counsel signs off on the corresponding packet.");
  lines.push("");
  for (const slug of slugs) {
    lines.push(`- [${slug}](./${slug}.md)`);
  }
  lines.push("");
  return lines.join("\n");
}

main().catch((err) => {
  process.stderr.write(`render-counsel-handoff-packets failed: ${String(err)}\n`);
  process.exit(1);
});
