/**
 * scripts/render-counsel-handoff-packets.ts
 *
 * Renders the per-vertical counsel-handoff packets so Conner can hand the
 * markdown directly to outside counsel without exposing the codebase.
 *
 * Run: `npx tsx scripts/render-counsel-handoff-packets.ts`
 *
 * Outputs:
 *   - `outputs/counsel-handoff-packets/<vertical>.md` (all verticals) + README
 *   - `outputs/counsel-handoff-<vertical>-<date>/PACKET.md` for each vertical
 *     in DATED_BUNDLES — the dated deliverable bundles for a specific
 *     counsel-handoff wave.
 *
 * The Markdown itself is produced by the shared `renderCounselPacketMarkdown`
 * renderer in `lib/agents/sentinel/render-counsel-packet.ts` — there is ONE
 * renderer so the docs never drift from the corpus (per
 * `feedback_no_silent_vendor_lock.md`'s no-divergence spirit). Every section
 * cites the source rule's citation URL + accessedAt
 * (`feedback_no_guesses_no_estimates.md`).
 *
 * Per the vertical-depth wave: rendered packets are counsel PREP material.
 * They carry the DRAFT badge + "sentinel is not firing on these yet"
 * disclaimer so counsel is not misled about deployment state.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  buildCounselHandoffPacket,
  listCorpusVerticals,
  loadCorpusFor,
  renderCounselPacketMarkdown,
} from "../lib/agents/sentinel";

const OUT_DIR = path.resolve(process.cwd(), "outputs/counsel-handoff-packets");

/**
 * Verticals that also get a dated standalone bundle this wave. The date is
 * the counsel-handoff wave date, matching the branch
 * (feat/mortgage-insurance-compliance-corpus-tightening-2026-06-03).
 */
const DATED_BUNDLES: Array<{ slug: string; label: string; date: string }> = [
  { slug: "mortgage", label: "Mortgage", date: "2026-06-03" },
  { slug: "insurance", label: "Insurance", date: "2026-06-03" },
  // 4-corpora tightening wave (feat/4-corpora-tightening-2026-06-06).
  { slug: "cpa", label: "CPA", date: "2026-06-06" },
  { slug: "ria", label: "RIA", date: "2026-06-06" },
  { slug: "law", label: "Law", date: "2026-06-06" },
  { slug: "title-escrow", label: "Title & Escrow", date: "2026-06-06" },
];

const VERTICAL_LABELS: Record<string, string> = {
  "real-estate": "Real Estate",
  mortgage: "Mortgage",
  insurance: "Insurance",
  "property-management": "Property Management",
  "title-escrow": "Title & Escrow",
  recruiting: "Recruiting",
  "home-services": "Home Services",
  cpa: "CPA",
  law: "Law",
  ria: "RIA",
};

function labelFor(slug: string): string {
  return VERTICAL_LABELS[slug] ?? slug;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const slugs = listCorpusVerticals();
  for (const slug of slugs) {
    const corpus = loadCorpusFor(slug);
    if (!corpus) continue;
    const packet = buildCounselHandoffPacket(corpus);
    const md = renderCounselPacketMarkdown(packet, {
      verticalLabel: labelFor(slug),
      generatedAt: corpus.metadata.lastReviewedAt,
    });
    const file = path.join(OUT_DIR, `${slug}.md`);
    await writeFile(file, md, "utf8");
    process.stdout.write(`wrote ${path.relative(process.cwd(), file)}\n`);
  }

  const index = renderIndex(slugs);
  const indexPath = path.join(OUT_DIR, "README.md");
  await writeFile(indexPath, index, "utf8");
  process.stdout.write(`wrote ${path.relative(process.cwd(), indexPath)}\n`);

  for (const bundle of DATED_BUNDLES) {
    const corpus = loadCorpusFor(bundle.slug);
    if (!corpus) {
      process.stderr.write(`skip dated bundle: no corpus for ${bundle.slug}\n`);
      continue;
    }
    const packet = buildCounselHandoffPacket(corpus);
    const md = renderCounselPacketMarkdown(packet, {
      verticalLabel: bundle.label,
      generatedAt: bundle.date,
    });
    const dir = path.resolve(
      process.cwd(),
      `outputs/counsel-handoff-${bundle.slug}-${bundle.date}`,
    );
    await mkdir(dir, { recursive: true });
    const file = path.join(dir, "PACKET.md");
    await writeFile(file, md, "utf8");
    process.stdout.write(`wrote ${path.relative(process.cwd(), file)}\n`);
  }
}

function renderIndex(slugs: string[]): string {
  const lines: string[] = [];
  lines.push("# Counsel-handoff packets — index");
  lines.push("");
  lines.push(
    "Per-vertical packets generated by `scripts/render-counsel-handoff-packets.ts` " +
      "from the sentinel corpus under `lib/agents/sentinel/corpus/` via the shared " +
      "`renderCounselPacketMarkdown` renderer.",
  );
  lines.push("");
  lines.push(
    "**For counsel:** each file contains (1) live literal triggers sentinel fires " +
      "on today, (2) candidate literal triggers awaiting phrase-by-phrase red-line, " +
      "(3) candidate regex triggers, (4) counsel-reference regulatory text, and " +
      "(5) questions for counsel with the most-ambiguous rules surfaced first.",
  );
  lines.push("");
  lines.push(
    "Every corpus below is DRAFT. Sentinel does not flip live for a vertical until " +
      "counsel signs off AND ops enables it via `COMPLIANCE_CORPUS_COUNSEL_REVIEWED`.",
  );
  lines.push("");
  for (const slug of slugs) {
    lines.push(`- [${labelFor(slug)}](./${slug}.md)`);
  }
  lines.push("");
  return lines.join("\n");
}

main().catch((err) => {
  process.stderr.write(`render-counsel-handoff-packets failed: ${String(err)}\n`);
  process.exit(1);
});
