/* eslint-disable @next/next/no-img-element -- plain <img> for /public brand
   illustrations, matching the PlainoScene convention: these marketing surfaces
   are unit-tested with react-dom/server renderToStaticMarkup in bare node:test,
   where next/image's loader config is absent and would throw. */
import Section from "@/components/Section";

// "How it works" — three supporting illustrations grounding the product loop
// (connect → draft → approve) in the vertical's own visual world. The artwork
// is the distinctive per-vertical illustration set generated by
// tools/brand/gen-vertical-scenes.mjs (public/brand/illustrations/<slug>/).
//
// Only the verticals with a generated illustration set render this section; any
// other slug returns null so the page is unaffected (additive). Keep this list
// in sync with the VERTICALS array in tools/brand/gen-vertical-scenes.mjs.
const ILLUSTRATED = new Set([
  "real-estate",
  "cpa",
  "law",
  "property-management",
  "general",
]);

export function hasHowItWorks(slug: string): boolean {
  return ILLUSTRATED.has(slug);
}

const STEPS = [
  {
    n: 1,
    title: "Connect your tools",
    body: "Plaino plugs into the email, calendar, and systems you already use — read-only to start, nothing changed on your side.",
  },
  {
    n: 2,
    title: "Plaino drafts the work",
    body: "What comes in becomes a ready-to-send draft, grounded in your real files and the way your practice actually works.",
  },
  {
    n: 3,
    title: "You approve, it goes out",
    body: "Nothing leaves the building without your sign-off. You stay in control of every send — the judgment stays yours.",
  },
] as const;

export default function VerticalHowItWorks({
  slug,
  verticalName,
}: {
  slug: string;
  verticalName: string;
}) {
  if (!hasHowItWorks(slug)) return null;

  return (
    <Section
      tone="deep"
      eyebrow="How it works"
      title="Three steps, and the work starts drafting itself."
      intro={`The same loop runs for every ${verticalName.toLowerCase()} workspace: connect what you already use, let Plaino draft, and approve before anything goes out.`}
    >
      <ol className="grid gap-6 md:grid-cols-3">
        {STEPS.map((step) => (
          <li
            key={step.n}
            className="flex flex-col border border-rule bg-paper"
          >
            <img
              src={`/brand/illustrations/${slug}/step-${step.n}.svg`}
              alt={`Step ${step.n}: ${step.title}`}
              width={640}
              height={480}
              className="w-full border-b border-rule"
            />
            <div className="flex flex-1 flex-col p-6">
              <p className="font-mono text-[11px] tracking-eyebrow uppercase text-clay">
                Step {step.n}
              </p>
              <p className="mt-2 font-display text-xl text-ink">{step.title}</p>
              <p className="mt-3 text-[15px] leading-relaxed text-ink-soft">
                {step.body}
              </p>
            </div>
          </li>
        ))}
      </ol>
    </Section>
  );
}
