import type { VerticalContent } from "../types";

// Source: `b2b_vertical_opportunity_analysis_2026-04-27.md` notes property
// management as a roadmap-fit vertical (operating-model analog to realty).
// No Phase 0 product_spec.md JTBD table — draft:true and capability-inbox
// flagged.

export const propertyManagement: VerticalContent = {
  slug: "property-management",
  name: "Property management",
  tier: "regular",

  hero: {
    eyebrow: "Roadmap vertical · Regular tier",
    headline: "The fleet for the small-portfolio property manager.",
    valueProp:
      "agentplain REPLACES tenant inbound triage and maintenance ticket routing, INTEGRATES with Buildium, AppFolio, Propertyware, and your accounting stack, and AUGMENTS the owner report cadence so landlords stop calling you for status.",
  },

  metaTitle: "agentplain for property managers — single-family and small-portfolio operators",
  metaDescription:
    "An agentic fleet for 50–500-door single-family and small-portfolio property management companies. Tenant inbound triage, maintenance ticket routing, rent-collection chase, lease renewal cadence, and owner reporting — coordinated across Buildium, AppFolio, Propertyware, and the work-order vendor stack.",

  jtbdTables: [
    {
      role: "Principal / portfolio owner",
      draft: true,
      rows: [
        {
          job: "Know which units are at-risk this week",
          when: "Monday morning",
          today: "Walk PMs, read maintenance email",
          withAgentplain:
            "Portfolio overview — units flagged for delinquency, open work orders >7 days, lease expiry <60 days",
        },
        {
          job: "Approve a non-routine maintenance spend",
          when: "Ad hoc, urgent",
          today: "Phone calls and texts; no audit trail",
          withAgentplain:
            "Work-approval queue — request, vendor estimate, owner-policy match, one-click approve with audit trail",
        },
        {
          job: "Send the monthly owner report",
          when: "First week of every month",
          today: "Generated by accounting, edited by hand, late",
          withAgentplain:
            "Owner-reporter agent drafts per-owner; principal signs and sends from their own system",
        },
      ],
    },
    {
      role: "Property manager",
      draft: true,
      rows: [
        {
          job: "Triage tenant inbound",
          when: "All day, every day",
          today: "Phone tag, scattered email, missed weekends",
          withAgentplain:
            "Tenant-inbound agent classifies (maintenance / payment / lease question), routes, drafts the first-touch reply",
        },
        {
          job: "Coordinate a maintenance work order",
          when: "Continuous, ~10–30 active per PM",
          today: "Vendor phone tag, lost paper trail",
          withAgentplain:
            "Work-order agent routes to the right vendor by trade + zone, drafts the tenant-access window, logs vendor confirmation",
        },
        {
          job: "Run lease-renewal outreach 90/60/30 days out",
          when: "Continuous calendar",
          today: "Manual template + spreadsheet reminder",
          withAgentplain:
            "Renewal agent runs the cadence with market-rent context attached; PM signs the offer",
        },
      ],
    },
    {
      role: "Accounting clerk",
      draft: true,
      rows: [
        {
          job: "Chase late rent",
          when: "1st–5th of the month, then 15th",
          today: "Form-letter merge, manual phone calls",
          withAgentplain:
            "Collections agent runs the cadence with tenant payment history attached; clerk signs the escalation step",
        },
        {
          job: "Reconcile owner draws",
          when: "Monthly",
          today: "Spreadsheet of trust-account exceptions",
          withAgentplain:
            "Books agent drafts the reconciliation; clerk reviews exceptions only",
        },
      ],
    },
  ],

  roi: {
    multiplier: "15x",
    inputCost: "Regular tier · $199 per seat (solo), sliding to $99 per seat (50–99 seats) — first month free",
    outputValue: "$36,000 / yr saved on PM-hour and delinquency reclamation",
    math:
      "1 PM @ $48k all-in × ~25% of day on tenant inbound and maintenance routing = $12k/yr per PM in labor reclamation. At 3 PMs that is $36k against 3 Regular-tier seats at $199/mo solo ($7,164/yr) — ~5x at three PMs, sliding to ~15x+ as a portfolio grows past 25 seats and per-seat drops to $119/mo. Delinquency-day compression of 2 days/month at $200/door in rent float × 200 doors = $80k/yr additional in worst-case operations (modeled as upside, not committed).",
    citation:
      "Pricing per `project_stripe_both_surfaces.md` (per-seat ladder, locked 2026-05-09). ROI band per `project_pricing_value_anchor.md`. PM-hour distribution and delinquency-float math pending primary-research validation — flagged in capability inbox. Buildium/AppFolio market dynamics referenced from public segment reporting; specific savings claims are operator-modeled, not customer-attested.",
  },

  claims: {
    replace: [
      "Phone-tag tenant inbound — replaced by triaged + drafted first-touch",
      "Manual maintenance vendor dispatch — replaced by trade+zone-aware routing",
      "Hand-built monthly owner reports — replaced by drafted per-owner reads",
      "Form-letter collections chase — replaced by history-aware cadence with PM in the loop",
    ],
    integrate: [
      "Buildium (PMS)",
      "AppFolio (PMS)",
      "Propertyware (PMS)",
      "Yardi Breeze (PMS)",
      "QuickBooks Online (trust accounting layer)",
      "Outlook + Microsoft 365 Graph",
      "Work-order vendor portals (varies by region)",
    ],
    augment: [
      "Owner-policy matching on every work order — drafts cite the policy line, never invent",
      "Renewal pricing — drafted with comparable-rent evidence from the local feed",
      "Compliance review on tenant communications — fair housing + state-specific notice rules",
      "Trust-accounting exception triage — drafted with bank-feed evidence attached",
    ],
  },

  integrations: {
    shipped: [],
    planned: [
      { name: "Buildium", category: "PMS" },
      { name: "AppFolio", category: "PMS" },
      { name: "Propertyware", category: "PMS" },
      { name: "Yardi Breeze", category: "PMS" },
      { name: "QuickBooks Online", category: "Accounting" },
      { name: "Outlook + M365 Graph", category: "Email + calendar" },
      { name: "Twilio Voice (inbound triage receiver)", category: "Telephony — inbound only" },
    ],
    plannedWindow: "Q3 2026",
  },

  valueLoopExample: {
    scenario:
      "Friday 4:53pm. Tenant maintenance request — water heater leaking, unit 4B.",
    before:
      "Triage in Buildium, check the work-order history, message the vendor, message the owner, schedule the visit, follow up Monday. ~25 minutes of inbox ping-pong over the weekend.",
    after:
      "The fleet classified the request as urgent water damage, pulled unit 4B's three prior plumbing tickets, drafted the vendor dispatch message, drafted the owner notification with the likely cost band, and proposed a Saturday morning slot. Everything queued for the property manager's review.",
    outcome:
      "One review, three approvals, one Saturday visit. The manager spends the weekend on owners and tenants, not on coordination.",
  },
};
